server:
  port: 9001

spring:
  application:
    name: xudong-im
  datasource:
    url: jdbc:mysql://116.62.114.198:3306/xudong?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: MiZhi001
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:   #下面为连接池的补充设置，应用到上面数据源中
      initialSize: 4 #初始化大小
      minIdle: 4 #最小
      maxActive: 32 #最大
      maxWait: 1000  #获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 30000 #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 5000 #一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

  data:
    mongodb:
      uri: mongodb://btbs_his:MiZhi001@47.96.89.84:27017/btbs_his

security:
  basic:
    enabled: false
