server:
  port: 9001

spring:
  application:
    name: xudong-im
  datasource:
    url: jdbc:mysql://116.62.114.198:3306/xudong?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: MiZhi001
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:   #下面为连接池的补充设置，应用到上面数据源中
      max-lifetime: 1000
      minimum-idle: 4
      idle-timeout: 1000
      maximum-pool-size: 32
      connection-test-query: SELECT 1
      connection-timeout: 2000
#      initialSize: 4 #最小
#      maxActive: 32 #最大
#      maxWait: 1000  #获取连接等待超时的时间
#      timeBetweenEvictionRunsMillis: 30000 #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      minEvictableIdleTimeMillis: 5000 #一个连接在池中最小生存的时间，单位是毫秒
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      testOnBorrow: true
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
  data:
    mongodb:
      uri: mongodb://btbs_financing:MiZhi001@47.96.89.84:27017/btbs_financing

  redis:
    host: 47.96.89.84
    #host: 127.0.0.1
    port: 6379
    password: MiZhi001
    #timeout: 3000
    jedis:
      pool:
        max-active: 16  #最大连接数,0为没有限制
        max-idle: 4   #最大等待连接中的数量, 0为没有限制
        min-idle: 1   #最小等待连接中的数量
        max-wait: 2000ms  #最大建立连接等待时间。如果超过此时间将接到异常
#    lettuce:
#      pool:
#        max-idle: 2
#        min-idle: 2
#        max-active: 2
#        max-wait: 2000ms
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  mvc:
    throw-exception-if-no-handler-found: true
    #spring.resources.add-mappings=false
  output:
    ansi:
      enabled: detect
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


security:
  basic:
    enabled: false

logging:
  pattern:
    console: "%date{dd HH:mm:ss} %level [%thread] %msg。%-60caller{1}"
  level:
    #org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: warn
    org.springframework.boot.autoconfigure.logging: warn
    org.springframework.web.socket: debug
    springfox.documentation: error
    io.swagger: error
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    java.sql.ResultSet: debug
    org.springframework.jdbc.core: TRACE
    com.xudong: debug

